package com.example.lazuardyapp.tutorselection

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector

data class Tutor(
    val id: Int,
    val name: String,
    val subject: String,
    val subjectIcon: ImageVector,
    val subjectIconColor: Color,
    val level: String,
    val rating: Double,
    val reviewCount: Int,
    val description: String,
    val studentCount: Int,
    val sessionCount: Int,
    val availability: String
)

val sampleTutors = listOf(
    Tutor(
        id = 1,
        name = "Budi Santoso",
        subject = "Matematika",
        subjectIcon = Icons.Default.Calculate,
        subjectIconColor = Color(0xFFC62828),
        level = "SMP & SMA",
        rating = 4.9,
        reviewCount = 50,
        description = "Tutor Matematika bersertifikat, ramah, dan berpengalaman lebih dari 5 tahun mengajar siswa SMP & SMA.",
        studentCount = 56,
        sessionCount = 224,
        availability = "Online"
    ),
    Tutor(
        id = 2,
        name = "Dewi Puspita",
        subject = "Matematika",
        subjectIcon = Icons.Default.Calculate,
        subjectIconColor = Color(0xFFC62828),
        level = "SD & SMP",
        rating = 4.8,
        reviewCount = 45,
        description = "Spesialis Matematika dasar, membuat angka menjadi mudah dipahami untuk level SD dan SMP.",
        studentCount = 42,
        sessionCount = 180,
        availability = "Online"
    ),
    Tutor(
        id = 3,
        name = "Rahmat Hidayat",
        subject = "Matematika",
        subjectIcon = Icons.Default.Calculate,
        subjectIconColor = Color(0xFFC62828),
        level = "SMA (UTBK Fokus)",
        rating = 4.7,
        reviewCount = 38,
        description = "Fokus pada persiapan UTBK dan ujian masuk universitas, menguasai Kalkulus dan Statistika.",
        studentCount = 65,
        sessionCount = 310,
        availability = "Online/Offline"
    ),
    Tutor(
        id = 4,
        name = "Sari Mustika",
        subject = "Matematika",
        subjectIcon = Icons.Default.Calculate,
        subjectIconColor = Color(0xFFC62828),
        level = "SMP",
        rating = 5.0,
        reviewCount = 60,
        description = "Menggunakan metode belajar interaktif dan menyenangkan agar siswa tidak takut pada Matematika.",
        studentCount = 70,
        sessionCount = 280,
        availability = "Offline"
    ),
    Tutor(
        id = 5,
        name = "Joko Prayogo",
        subject = "Matematika",
        subjectIcon = Icons.Default.Calculate,
        subjectIconColor = Color(0xFFC62828),
        level = "SMA",
        rating = 4.6,
        reviewCount = 25,
        description = "Mahasiswa Teknik yang berpengalaman membantu PR dan tugas Matematika tingkat SMA.",
        studentCount = 30,
        sessionCount = 150,
        availability = "Online"
    ),
    Tutor(
        id = 6,
        name = "Lina Marwati",
        subject = "Matematika",
        subjectIcon = Icons.Default.Calculate,
        subjectIconColor = Color(0xFFC62828),
        level = "SMP & SMA",
        rating = 4.9,
        reviewCount = 55,
        description = "Lulusan terbaik dari jurusan Matematika terapan, fokus pada pemecahan masalah kompleks.",
        studentCount = 58,
        sessionCount = 230,
        availability = "Online/Offline"
    ),
    Tutor(
        id = 7,
        name = "Siti Rahmawati",
        subject = "Bahasa Inggris",
        subjectIcon = Icons.Default.Language,
        subjectIconColor = Color(0xFF00BCD4),
        level = "SD, SMP & SMA",
        rating = 4.8,
        reviewCount = 25,
        description = "Tutor Bahasa Inggris profesional dengan metode pembelajaran interaktif dan fokus pada speaking serta grammar.",
        studentCount = 34,
        sessionCount = 120,
        availability = "Online"
    ),
    Tutor(
        id = 8,
        name = "Michael T.",
        subject = "Bahasa Inggris",
        subjectIcon = Icons.Default.Language,
        subjectIconColor = Color(0xFF00BCD4),
        level = "SMA & Mahasiswa",
        rating = 4.9,
        reviewCount = 40,
        description = "Native speaker yang fokus pada IELTS, TOEFL, dan percakapan bisnis.",
        studentCount = 45,
        sessionCount = 200,
        availability = "Online"
    ),
    Tutor(
        id = 9,
        name = "Ayu Lestari",
        subject = "Bahasa Inggris",
        subjectIcon = Icons.Default.Language,
        subjectIconColor = Color(0xFF00BCD4),
        level = "SD & SMP",
        rating = 4.7,
        reviewCount = 30,
        description = "Mengajar Bahasa Inggris dengan lagu dan permainan, cocok untuk pemula dan anak-anak.",
        studentCount = 50,
        sessionCount = 150,
        availability = "Offline"
    ),
    Tutor(
        id = 10,
        name = "Faisal Malik",
        subject = "Bahasa Inggris",
        subjectIcon = Icons.Default.Language,
        subjectIconColor = Color(0xFF00BCD4),
        level = "SMA (UTBK & TOEFL)",
        rating = 4.6,
        reviewCount = 20,
        description = "Spesialis bagian Reading Comprehension dan Vocabulary untuk ujian masuk PTN.",
        studentCount = 35,
        sessionCount = 180,
        availability = "Online"
    ),
    Tutor(
        id = 11,
        name = "Maria Claudia",
        subject = "Bahasa Inggris",
        subjectIcon = Icons.Default.Language,
        subjectIconColor = Color(0xFF00BCD4),
        level = "Semua Level",
        rating = 5.0,
        reviewCount = 65,
        description = "Tutor yang sabar dan teliti, membantu meningkatkan rasa percaya diri dalam berbicara Bahasa Inggris.",
        studentCount = 75,
        sessionCount = 300,
        availability = "Online/Offline"
    ),
    Tutor(
        id = 12,
        name = "Ahmad Fauzi",
        subject = "Fisika",
        subjectIcon = Icons.Default.FlashOn,
        subjectIconColor = Color(0xFF03A9F4),
        level = "SMA",
        rating = 4.7,
        reviewCount = 38,
        description = "Tutor Fisika berpengalaman membantu persiapan UTBK dan ujian dengan pendekatan logis dan mudah dipahami.",
        studentCount = 42,
        sessionCount = 180,
        availability = "Online/Offline"
    ),
    Tutor(
        id = 13,
        name = "Gita Savitri",
        subject = "Fisika",
        subjectIcon = Icons.Default.FlashOn,
        subjectIconColor = Color(0xFF03A9F4),
        level = "SMA & Mahasiswa",
        rating = 4.9,
        reviewCount = 50,
        description = "Menguasai Mekanika Klasik dan Elektromagnetisme. Cocok untuk yang ingin masuk jurusan Teknik.",
        studentCount = 60,
        sessionCount = 250,
        availability = "Online"
    ),
    Tutor(
        id = 14,
        name = "Hendra Wijaya",
        subject = "Fisika",
        subjectIcon = Icons.Default.FlashOn,
        subjectIconColor = Color(0xFF03A9F4),
        level = "SMP",
        rating = 4.6,
        reviewCount = 22,
        description = "Membuat konsep Fisika yang abstrak menjadi visual dan mudah dicerna untuk siswa SMP.",
        studentCount = 30,
        sessionCount = 100,
        availability = "Offline"
    ),
    Tutor(
        id = 15,
        name = "Maya Safira",
        subject = "Fisika",
        subjectIcon = Icons.Default.FlashOn,
        subjectIconColor = Color(0xFF03A9F4),
        level = "SMA",
        rating = 4.8,
        reviewCount = 44,
        description = "Mengajar Fisika dengan fokus pada pemecahan soal dan trik cepat. Lulusan Fisika ITB.",
        studentCount = 55,
        sessionCount = 220,
        availability = "Online"
    ),
    Tutor(
        id = 16,
        name = "Bima Sakti",
        subject = "Fisika",
        subjectIcon = Icons.Default.FlashOn,
        subjectIconColor = Color(0xFF03A9F4),
        level = "SMA (Kuantum & Modern)",
        rating = 4.5,
        reviewCount = 15,
        description = "Fokus pada materi Fisika modern, relativitas, dan kuantum.",
        studentCount = 25,
        sessionCount = 90,
        availability = "Online/Offline"
    ),
    Tutor(
        id = 17,
        name = "Citra Dewi",
        subject = "Kimia",
        subjectIcon = Icons.Default.Science,
        subjectIconColor = Color(0xFFFFC107),
        level = "SMA",
        rating = 4.9,
        reviewCount = 60,
        description = "Pakar Kimia Organik dan Anorganik. Menggunakan eksperimen visual dalam mengajar.",
        studentCount = 65,
        sessionCount = 280,
        availability = "Online"
    ),
    Tutor(
        id = 18,
        name = "Ferry Setiawan",
        subject = "Kimia",
        subjectIcon = Icons.Default.Science,
        subjectIconColor = Color(0xFFFFC107),
        level = "SMA (UTBK)",
        rating = 4.7,
        reviewCount = 40,
        description = "Membantu persiapan tes masuk dengan fokus pada stoikiometri dan laju reaksi.",
        studentCount = 50,
        sessionCount = 200,
        availability = "Online/Offline"
    ),
    Tutor(
        id = 19,
        name = "Nadia Khairani",
        subject = "Kimia",
        subjectIcon = Icons.Default.Science,
        subjectIconColor = Color(0xFFFFC107),
        level = "SMP & SMA",
        rating = 4.8,
        reviewCount = 55,
        description = "Menyederhanakan materi Kimia yang rumit menjadi mudah dan logis.",
        studentCount = 70,
        sessionCount = 300,
        availability = "Offline"
    ),
    Tutor(
        id = 20,
        name = "Wayan Putra",
        subject = "Kimia",
        subjectIcon = Icons.Default.Science,
        subjectIconColor = Color(0xFFFFC107),
        level = "SMA",
        rating = 4.6,
        reviewCount = 35,
        description = "Pengajar Kimia Terapan dengan pengalaman riset di bidang polimer.",
        studentCount = 45,
        sessionCount = 150,
        availability = "Online"
    ),
    Tutor(
        id = 21,
        name = "Rosa Indah",
        subject = "Kimia",
        subjectIcon = Icons.Default.Science,
        subjectIconColor = Color(0xFFFFC107),
        level = "SMP",
        rating = 4.9,
        reviewCount = 58,
        description = "Guru privat Kimia yang fokus pada peningkatan nilai rapot dan pemahaman dasar.",
        studentCount = 68,
        sessionCount = 290,
        availability = "Online"
    ),
    Tutor(
        id = 22,
        name = "Diana Santika",
        subject = "Biologi",
        subjectIcon = Icons.Default.LocalHospital,
        subjectIconColor = Color(0xFF4CAF50),
        level = "SMA",
        rating = 4.8,
        reviewCount = 45,
        description = "Lulusan Kedokteran. Menguasai Genetika, Sel, dan Fisiologi Tumbuhan.",
        studentCount = 52,
        sessionCount = 210,
        availability = "Online"
    ),
    Tutor(
        id = 23,
        name = "Eko Prasetyo",
        subject = "Biologi",
        subjectIcon = Icons.Default.LocalHospital,
        subjectIconColor = Color(0xFF4CAF50),
        level = "SMP & SMA",
        rating = 4.7,
        reviewCount = 35,
        description = "Menyajikan materi Biologi dengan studi kasus nyata, membuat belajar jadi seru.",
        studentCount = 48,
        sessionCount = 190,
        availability = "Offline"
    ),
    Tutor(
        id = 24,
        name = "Rina Agustin",
        subject = "Biologi",
        subjectIcon = Icons.Default.LocalHospital,
        subjectIconColor = Color(0xFF4CAF50),
        level = "SMA (UTBK)",
        rating = 4.9,
        reviewCount = 55,
        description = "Fokus pada materi Biologi yang sering keluar di UTBK, termasuk Evolusi dan Ekologi.",
        studentCount = 60,
        sessionCount = 250,
        availability = "Online/Offline"
    ),
    Tutor(
        id = 25,
        name = "Adi Nugroho",
        subject = "Biologi",
        subjectIcon = Icons.Default.LocalHospital,
        subjectIconColor = Color(0xFF4CAF50),
        level = "SMP",
        rating = 4.6,
        reviewCount = 30,
        description = "Tutor Biologi dasar, cocok untuk meningkatkan pemahaman konsep awal.",
        studentCount = 40,
        sessionCount = 150,
        availability = "Online"
    ),
    Tutor(
        id = 26,
        name = "Lisa Permata",
        subject = "Biologi",
        subjectIcon = Icons.Default.LocalHospital,
        subjectIconColor = Color(0xFF4CAF50),
        level = "SMA",
        rating = 5.0,
        reviewCount = 62,
        description = "Berpengalaman mengajar Biologi untuk kurikulum internasional.",
        studentCount = 72,
        sessionCount = 320,
        availability = "Online"
    ),
    Tutor(
        id = 27,
        name = "Hasan Basri",
        subject = "Bahasa Indonesia",
        subjectIcon = Icons.Default.Book,
        subjectIconColor = Color(0xFF795548),
        level = "SMP & SMA",
        rating = 4.8,
        reviewCount = 40,
        description = "Spesialisasi Paragraf, Ejaan, dan Tata Bahasa. Membantu tugas menulis esai.",
        studentCount = 50,
        sessionCount = 200,
        availability = "Online/Offline"
    ),
    Tutor(
        id = 28,
        name = "Indah Sari",
        subject = "Bahasa Indonesia",
        subjectIcon = Icons.Default.Book,
        subjectIconColor = Color(0xFF795548),
        level = "SMA (UTBK)",
        rating = 4.9,
        reviewCount = 55,
        description = "Fokus pada penalaran Bahasa Indonesia dan persiapan tes masuk PTN.",
        studentCount = 60,
        sessionCount = 250,
        availability = "Online"
    ),
    Tutor(
        id = 29,
        name = "Kemal Atmaja",
        subject = "Bahasa Indonesia",
        subjectIcon = Icons.Default.Book,
        subjectIconColor = Color(0xFF795548),
        level = "SMP",
        rating = 4.7,
        reviewCount = 35,
        description = "Guru B. Indonesia yang kreatif, membuat materi sastra dan pantun jadi menarik.",
        studentCount = 45,
        sessionCount = 180,
        availability = "Offline"
    ),
    Tutor(
        id = 30,
        name = "Nia Ramadhani",
        subject = "Bahasa Indonesia",
        subjectIcon = Icons.Default.Book,
        subjectIconColor = Color(0xFF795548),
        level = "SD & SMP",
        rating = 5.0,
        reviewCount = 65,
        description = "Tutor ramah yang membantu meningkatkan kemampuan membaca dan menulis anak.",
        studentCount = 75,
        sessionCount = 300,
        availability = "Online"
    ),
    Tutor(
        id = 31,
        name = "Sigit Pramono",
        subject = "Bahasa Indonesia",
        subjectIcon = Icons.Default.Book,
        subjectIconColor = Color(0xFF795548),
        level = "SMA",
        rating = 4.6,
        reviewCount = 30,
        description = "Berpengalaman di bidang jurnalistik, fokus pada penulisan formal dan non-fiksi.",
        studentCount = 40,
        sessionCount = 150,
        availability = "Online/Offline"
    ),
    Tutor(
        id = 34,
        name = "Kevin Susanto",
        subject = "Informatika",
        subjectIcon = Icons.Default.Computer,
        subjectIconColor = Color(0xFF3F51B5),
        level = "SMA & Mahasiswa",
        rating = 4.9,
        reviewCount = 70,
        description = "Pakar algoritma dan pemrograman dasar (Python/Java). Lulusan Ilmu Komputer.",
        studentCount = 80,
        sessionCount = 350,
        availability = "Online"
    ),
    Tutor(
        id = 35,
        name = "Putri Amelia",
        subject = "Informatika",
        subjectIcon = Icons.Default.Computer,
        subjectIconColor = Color(0xFF3F51B5),
        level = "SMA",
        rating = 4.8,
        reviewCount = 55,
        description = "Menguasai jaringan komputer dan keamanan siber tingkat dasar untuk SMA.",
        studentCount = 65,
        sessionCount = 280,
        availability = "Online/Offline"
    ),
    Tutor(
        id = 36,
        name = "Yoga Pratama",
        subject = "Informatika",
        subjectIcon = Icons.Default.Computer,
        subjectIconColor = Color(0xFF3F51B5),
        level = "SMA (UTBK)",
        rating = 4.7,
        reviewCount = 45,
        description = "Fokus pada persiapan materi TPS Kuantitatif dan Penalaran Matematika berbasis IT.",
        studentCount = 55,
        sessionCount = 220,
        availability = "Online"
    ),
    Tutor(
        id = 37,
        name = "Ratna Dewi",
        subject = "Informatika",
        subjectIcon = Icons.Default.Computer,
        subjectIconColor = Color(0xFF3F51B5),
        level = "SMP & SMA",
        rating = 5.0,
        reviewCount = 80,
        description = "Pengajar yang sabar, mengajarkan logika pemrograman dari nol.",
        studentCount = 90,
        sessionCount = 400,
        availability = "Offline"
    ),
    Tutor(
        id = 38,
        name = "Herman Budi",
        subject = "Informatika",
        subjectIcon = Icons.Default.Computer,
        subjectIconColor = Color(0xFF3F51B5),
        level = "SMA",
        rating = 4.6,
        reviewCount = 35,
        description = "Membantu proyek sekolah dan coding dasar menggunakan C++.",
        studentCount = 45,
        sessionCount = 180,
        availability = "Online"
    ),
    Tutor(
        id = 39,
        name = "Melly Andriani",
        subject = "Informatika",
        subjectIcon = Icons.Default.Computer,
        subjectIconColor = Color(0xFF3F51B5),
        level = "SMA & Mahasiswa",
        rating = 4.9,
        reviewCount = 65,
        description = "Spesialis basis data (SQL) dan pengembangan web dasar.",
        studentCount = 75,
        sessionCount = 320,
        availability = "Online/Offline"
    ),
    Tutor(
        id = 40,
        name = "Rizki Fajar",
        subject = "PKN",
        subjectIcon = Icons.Default.Policy,
        subjectIconColor = Color(0xFFFFA000),
        level = "SMP & SMA",
        rating = 4.7,
        reviewCount = 40,
        description = "Membuat materi kewarganegaraan menjadi relevan dengan isu-isu terkini.",
        studentCount = 50,
        sessionCount = 200,
        availability = "Online"
    ),
    Tutor(
        id = 41,
        name = "Sinta Dewi",
        subject = "PKN",
        subjectIcon = Icons.Default.Policy,
        subjectIconColor = Color(0xFFFFA000),
        level = "SMA (SOSHUM)",
        rating = 4.8,
        reviewCount = 50,
        description = "Menguasai materi Konstitusi dan Pancasila. Fokus pada analisis kasus.",
        studentCount = 60,
        sessionCount = 250,
        availability = "Online/Offline"
    ),
    Tutor(
        id = 42,
        name = "Eka Setiawan",
        subject = "PKN",
        subjectIcon = Icons.Default.Policy,
        subjectIconColor = Color(0xFFFFA000),
        level = "SMP",
        rating = 4.9,
        reviewCount = 60,
        description = "Mendorong diskusi kritis dan pemahaman hak dan kewajiban warga negara.",
        studentCount = 70,
        sessionCount = 300,
        availability = "Offline"
    ),
    Tutor(
        id = 43,
        name = "Fara Lutfi",
        subject = "PKN",
        subjectIcon = Icons.Default.Policy,
        subjectIconColor = Color(0xFFFFA000),
        level = "SMA",
        rating = 4.6,
        reviewCount = 30,
        description = "Lulusan Hukum Tata Negara, membantu memahami struktur pemerintahan.",
        studentCount = 40,
        sessionCount = 150,
        availability = "Online"
    ),
    Tutor(
        id = 44,
        name = "Bayu Adityo",
        subject = "PKN",
        subjectIcon = Icons.Default.Policy,
        subjectIconColor = Color(0xFFFFA000),
        level = "SMA",
        rating = 5.0,
        reviewCount = 75,
        description = "Tutor favorit yang selalu update dengan kebijakan publik terbaru.",
        studentCount = 85,
        sessionCount = 380,
        availability = "Online/Offline"
    ),
    Tutor(
        id = 45,
        name = "Dimas Wiratama",
        subject = "Sejarah Indonesia",
        subjectIcon = Icons.Default.HistoryEdu,
        subjectIconColor = Color(0xFF9C27B0),
        level = "SMA (SOSHUM)",
        rating = 4.8,
        reviewCount = 55,
        description = "Spesialisasi Sejarah Kemerdekaan dan Orde Baru. Menggunakan peta dan visualisasi.",
        studentCount = 65,
        sessionCount = 270,
        availability = "Online"
    ),
    Tutor(
        id = 46,
        name = "Nining Sari",
        subject = "Sejarah Indonesia",
        subjectIcon = Icons.Default.HistoryEdu,
        subjectIconColor = Color(0xFF9C27B0),
        level = "SMP & SMA",
        rating = 4.7,
        reviewCount = 45,
        description = "Membantu mengingat tanggal dan kronologi dengan teknik menghafal yang efektif.",
        studentCount = 55,
        sessionCount = 220,
        availability = "Offline"
    ),
    Tutor(
        id = 47,
        name = "Andi Prasetyo",
        subject = "Sejarah Indonesia",
        subjectIcon = Icons.Default.HistoryEdu,
        subjectIconColor = Color(0xFF9C27B0),
        level = "SMA (UTBK)",
        rating = 4.9,
        reviewCount = 65,
        description = "Fokus pada materi yang diujikan dalam seleksi PTN dan pemahaman konsep kolonialisme.",
        studentCount = 75,
        sessionCount = 320,
        availability = "Online/Offline"
    ),
    Tutor(
        id = 48,
        name = "Rismawati",
        subject = "Sejarah Indonesia",
        subjectIcon = Icons.Default.HistoryEdu,
        subjectIconColor = Color(0xFF9C27B0),
        level = "SMP",
        rating = 4.6,
        reviewCount = 30,
        description = "Guru Sejarah yang menyukai cerita pahlawan dan kerajaan nusantara.",
        studentCount = 40,
        sessionCount = 150,
        availability = "Online"
    ),
    Tutor(
        id = 49,
        name = "Seno Aji",
        subject = "Sejarah Indonesia",
        subjectIcon = Icons.Default.HistoryEdu,
        subjectIconColor = Color(0xFF9C27B0),
        level = "SMA",
        rating = 4.5,
        reviewCount = 25,
        description = "Menganalisis sumber-sumber primer Sejarah Indonesia.",
        studentCount = 35,
        sessionCount = 120,
        availability = "Online"
    ),
    Tutor(
        id = 50,
        name = "Putu Gede",
        subject = "Geografi",
        subjectIcon = Icons.Default.Public,
        subjectIconColor = Color(0xFF009688),
        level = "SMA (SOSHUM)",
        rating = 4.9,
        reviewCount = 70,
        description = "Pakar Kartografi dan Sistem Informasi Geografis (SIG). Lulusan Geografi UGM.",
        studentCount = 80,
        sessionCount = 350,
        availability = "Online"
    ),
    Tutor(
        id = 51,
        name = "Rudi Hartono",
        subject = "Geografi",
        subjectIcon = Icons.Default.Public,
        subjectIconColor = Color(0xFF009688),
        level = "SMP & SMA",
        rating = 4.7,
        reviewCount = 45,
        description = "Membuat materi litosfer dan hidrosfer jadi mudah dipahami dengan visualisasi 3D.",
        studentCount = 55,
        sessionCount = 220,
        availability = "Offline"
    ),
    Tutor(
        id = 52,
        name = "Lia Agustina",
        subject = "Geografi",
        subjectIcon = Icons.Default.Public,
        subjectIconColor = Color(0xFF009688),
        level = "SMA (UTBK)",
        rating = 4.8,
        reviewCount = 60,
        description = "Fokus pada persiapan UTBK dan interpretasi peta tematik.",
        studentCount = 70,
        sessionCount = 300,
        availability = "Online/Offline"
    ),
    Tutor(
        id = 53,
        name = "Doni Setiadi",
        subject = "Geografi",
        subjectIcon = Icons.Default.Public,
        subjectIconColor = Color(0xFF009688),
        level = "SMA",
        rating = 4.6,
        reviewCount = 30,
        description = "Ahli Geografi Fisik dan Lingkungan.",
        studentCount = 40,
        sessionCount = 150,
        availability = "Online"
    ),
    Tutor(
        id = 54,
        name = "Wulan Sari",
        subject = "Geografi",
        subjectIcon = Icons.Default.Public,
        subjectIconColor = Color(0xFF009688),
        level = "SMP",
        rating = 5.0,
        reviewCount = 85,
        description = "Mengajar tentang kekayaan alam dan budaya Indonesia.",
        studentCount = 95,
        sessionCount = 400,
        availability = "Online"
    ),
    Tutor(
        id = 55,
        name = "Amir Hamzah",
        subject = "Ekonomi",
        subjectIcon = Icons.Default.MonetizationOn,
        subjectIconColor = Color(0xFF455A64),
        level = "SMA (SOSHUM)",
        rating = 4.9,
        reviewCount = 65,
        description = "Spesialis Ekonomi Makro, Fiskal, dan Moneter. Lulusan Akuntansi Terbaik.",
        studentCount = 75,
        sessionCount = 320,
        availability = "Online"
    ),
    Tutor(
        id = 56,
        name = "Bela Anjani",
        subject = "Ekonomi",
        subjectIcon = Icons.Default.MonetizationOn,
        subjectIconColor = Color(0xFF455A64),
        level = "SMA (UTBK)",
        rating = 4.8,
        reviewCount = 55,
        description = "Fokus pada persiapan soal-soal Akuntansi dan Mikro Ekonomi sulit di UTBK.",
        studentCount = 65,
        sessionCount = 280,
        availability = "Online/Offline"
    ),
    Tutor(
        id = 57,
        name = "Candra Kirana",
        subject = "Ekonomi",
        subjectIcon = Icons.Default.MonetizationOn,
        subjectIconColor = Color(0xFF455A64),
        level = "SMA",
        rating = 4.7,
        reviewCount = 45,
        description = "Mengajar prinsip dasar Ekonomi dan pasar modal.",
        studentCount = 55,
        sessionCount = 220,
        availability = "Offline"
    ),
    Tutor(
        id = 58,
        name = "Dian Pratama",
        subject = "Ekonomi",
        subjectIcon = Icons.Default.MonetizationOn,
        subjectIconColor = Color(0xFF455A64),
        level = "SMA",
        rating = 4.6,
        reviewCount = 35,
        description = "Berpengalaman membantu PR dan tugas Akuntansi perusahaan jasa.",
        studentCount = 45,
        sessionCount = 180,
        availability = "Online"
    ),
    Tutor(
        id = 59,
        name = "Eva Yolanda",
        subject = "Ekonomi",
        subjectIcon = Icons.Default.MonetizationOn,
        subjectIconColor = Color(0xFF455A64),
        level = "SMA",
        rating = 5.0,
        reviewCount = 75,
        description = "Menyederhanakan konsep kurva penawaran dan permintaan.",
        studentCount = 85,
        sessionCount = 380,
        availability = "Online"
    ),
    Tutor(
        id = 60,
        name = "Farid Husein",
        subject = "Sosiologi",
        subjectIcon = Icons.Default.People,
        subjectIconColor = Color(0xFF673AB7),
        level = "SMA (SOSHUM)",
        rating = 4.8,
        reviewCount = 55,
        description = "Pakar Sosiologi Konflik dan Perubahan Sosial. Menggunakan studi kasus terbaru.",
        studentCount = 65,
        sessionCount = 280,
        availability = "Online"
    ),
    Tutor(
        id = 61,
        name = "Gita Sari",
        subject = "Sosiologi",
        subjectIcon = Icons.Default.People,
        subjectIconColor = Color(0xFF673AB7),
        level = "SMA (UTBK)",
        rating = 4.9,
        reviewCount = 60,
        description = "Fokus pada materi Sosiologi yang berhubungan dengan Antropologi untuk UTBK.",
        studentCount = 70,
        sessionCount = 300,
        availability = "Online/Offline"
    ),
    Tutor(
        id = 62,
        name = "Hari Nugroho",
        subject = "Sosiologi",
        subjectIcon = Icons.Default.People,
        subjectIconColor = Color(0xFF673AB7),
        level = "SMA",
        rating = 4.7,
        reviewCount = 45,
        description = "Membantu memahami konsep diferensiasi dan stratifikasi sosial.",
        studentCount = 55,
        sessionCount = 220,
        availability = "Offline"
    ),
    Tutor(
        id = 63,
        name = "Intan Permata",
        subject = "Sosiologi",
        subjectIcon = Icons.Default.People,
        subjectIconColor = Color(0xFF673AB7),
        level = "SMA",
        rating = 4.6,
        reviewCount = 35,
        description = "Mengajarkan metode penelitian sosial dan observasi.",
        studentCount = 45,
        sessionCount = 180,
        availability = "Online"
    ),
    Tutor(
        id = 64,
        name = "Jaya Kusuma",
        subject = "Sosiologi",
        subjectIcon = Icons.Default.People,
        subjectIconColor = Color(0xFF673AB7),
        level = "SMA",
        rating = 5.0,
        reviewCount = 78,
        description = "Tutor yang menekankan relevansi teori Sosiologi dalam kehidupan sehari-hari.",
        studentCount = 88,
        sessionCount = 390,
        availability = "Online"
    )
)